version "3.7"
services:
  db:
    image: postgres:16
    container_name: db_app
    env_file:
      - .env-non-dev
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: conf_shed_app
    command: ["/conf_shed_app/app.sh"]
    ports:
      - 7890:8000
    depends_on:
      - db