"""update_shedule

Revision ID: 25cf7c32d055
Revises: 2d5b576b167f
Create Date: 2024-10-11 21:36:07.598196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25cf7c32d055'
down_revision: Union[str, None] = '2d5b576b167f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shedule', sa.Column('pr_name', sa.String(), nullable=False))
    op.add_column('shedule', sa.Column('presenter', sa.String(), nullable=False))
    op.alter_column('shedule', 'pr_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shedule', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('shedule_room_id_fkey', 'shedule', type_='foreignkey')
    op.drop_constraint('shedule_pr_id_fkey', 'shedule', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('shedule_pr_id_fkey', 'shedule', 'presentation', ['pr_id'], ['id'])
    op.create_foreign_key('shedule_room_id_fkey', 'shedule', 'room', ['room_id'], ['id'])
    op.alter_column('shedule', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('shedule', 'pr_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('shedule', 'presenter')
    op.drop_column('shedule', 'pr_name')
    # ### end Alembic commands ###
